"""empty message

Revision ID: b02633b88546
Revises: 4a1a60dd235c
Create Date: 2021-07-12 16:53:03.084533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02633b88546'
down_revision = '4a1a60dd235c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('plan', sa.String(), nullable=False))
    op.add_column('deals', sa.Column('duration', sa.Text(), nullable=False))
    op.drop_column('deals', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('deals', 'duration')
    op.drop_column('deals', 'plan')
    # ### end Alembic commands ###
